export enum CodigosError {
  NO_AUTENTICADO = 'NO_AUTENTICADO',
  NO_AUTORIZADO = 'NO_AUTORIZADO',
  USUARIO_NO_ENCONTRADO = 'USUARIO_NO_ENCONTRADO',
  CONTRASENA_INVALIDA = 'CONTRASENA_INVALIDA',
  AD_NO_DISPONIBLE = 'AD_NO_DISPONIBLE',
  CARNET_REGISTRO_DUPLICADO = 'CARNET_REGISTRO_DUPLICADO',
  CARNET_NO_ENCONTRADO = 'CARNET_NO_ENCONTRADO',
  ARCHIVO_INVALIDO = 'ARCHIVO_INVALIDO',
  ORACLE_ERROR = 'ORACLE_ERROR',
  SQL_SERVER_ERROR = 'SQL_SERVER_ERROR',
  VALIDACION = 'VALIDACION',
  ERROR_INTERNO = 'ERROR_INTERNO',
}
