export enum AccionHistorial {
  ASIGNAR = 'ASIGNAR',
  ELIMINAR = 'ELIMINAR',
  ACTIVAR = 'ACTIVAR',
  DESACTIVAR = 'DESACTIVAR',
  CAMBIO_FRECUENCIA = 'CAMBIO_FRECUENCIA',
  CAMBIO_ESTATUS = 'CAMBIO_ESTATUS',
}
